version: "3"
services:  
  php-container:
    container_name: street-fighter-php
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./:/var/www/html  
    ports:
      - 5000:80  
    depends_on:   
      - db
  db:
    platform: linux/x86_64
    container_name: street-fighter
    image: mysql:latest
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_COLLATION: utf8mb4_unicode_ci
      

  
